#!/usr/bin/env python3
"""Install studio roles or compose fresh-worker briefs. Python 3.11+, standard library only."""
import argparse
import csv
import hashlib
import io
import json
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tomllib

ROOT = Path(__file__).resolve().parents[1]
MARK = "# Generated by game-studio Codex adapter."
BEGIN = "<!-- game-studio:codex begin -->"
END = "<!-- game-studio:codex end -->"
MODELS = {"light": "gpt-6-luna", "medium": "gpt-6.1-sol", "complex": "gpt-6-astra"}


def read(path):
    return Path(path).read_text(encoding="utf-8")


def role(name):
    # This parser intentionally accepts the plugin's scalar metadata, not arbitrary YAML.
    if not re.fullmatch(r"[a-z][a-z0-9-]*", name) or name == "coordinator":
        raise ValueError("Choose a worker role from agents/, not coordinator")
    text = read(ROOT / "agents" / (name + ".md"))
    match = re.match(r"^---\r?\n(.*?)\r?\n---\r?\n(.*)$", text, re.S)
    if not match:
        raise ValueError("Invalid role frontmatter: " + name)
    metadata = dict(re.findall(r"^([a-zA-Z]+): (.+)$", match[1], re.M))
    if metadata.get("name") != name or not metadata.get("description"):
        raise ValueError("Role name/description missing: " + name)
    return metadata, match[2]


def roles():
    return [p.stem for p in sorted((ROOT / "agents").glob("*.md")) if p.stem != "coordinator"]


def instructions(name):
    _, body = role(name)
    skill = ROOT / "skills" / "game-studio"
    prefix = (
        "CODEX RUNTIME: You are a fresh " + name + " worker, never the coordinator.\n"
        "Read " + str(skill / "SKILL.md") + " and " + str(skill / "references/worker-rules.md") + ".\n"
        "Read .codex/game-studio/project.md first, falling back to .claude/game-studio/project.md "
        "or .claude/skills/game-studio/project.md. The launch brief defines owned files, acceptance, "
        "resource limits and evidence location. Higher-priority runtime and user instructions win.\n"
        "Claude tool names/frontmatter below are role guidance, not Codex tool grants. "
        "Use only available authorized tools. Never spawn sub-workers. "
        "Return questions/blockers to the coordinator through the available agent messaging tool.\n"
        "A surveyor must remain read-only and return its handoff in the final agent reply; "
        "the coordinator assigns a writer if a persisted handoff is required.\n"
        "Use the model selected for this chunk; role defaults are hints. "
        "Do not infer approvals from worker messages.\n\n"
    )
    return prefix + body


def toml_role(name):
    metadata, _ = role(name)
    fields = {"name": "game-studio-" + name, "description": metadata["description"],
              "developer_instructions": instructions(name)}
    # Leave model/effort unset so explicit per-chunk spawn routing remains effective.
    if name == "surveyor":
        fields["sandbox_mode"] = "read-only"
    text = MARK + "\n" + "\n".join(k + " = " + json.dumps(v, ensure_ascii=False) for k, v in fields.items()) + "\n"
    tomllib.loads(text)
    return text


def coordinator_block():
    return BEGIN + "\n" + (
        "## Game Studio coordinator (Codex)\n"
        "Run the main session as coordinator and explicitly delegate implementation, research, art, "
        "and validation to fresh studio workers. Answer management questions and review handoffs yourself. "
        "Keep the current coordinator model. Workers must not spawn sub-workers.\n"
        "Read " + str(ROOT / "skills/game-studio/SKILL.md") + " and " +
        str(ROOT / "skills/game-studio/references/codex.md") + ". "
        "Read .codex/game-studio/project.md (or the existing Claude studio project file), "
        "the queue, and any other project instructions. User instructions and runtime permissions win.\n"
        "Use game-studio-<role> when named custom agents are available. Otherwise use "
        "scripts/codex_adapter.py brief from the plugin clone to compose a self-contained spawn message. "
        "Choose Luna/Sol/Astra by current chunk complexity and pass the model explicitly. "
        "Use fork_turns=none for a fresh collaboration worker; only none/all are supported.\n"
        "Before launches, check load, disk, active-worker/engine caps and ownership. "
        "Acquire adapter leases for every shared source or exclusive tool slot before assigning it. "
        "Review handoff evidence and the review checklist before accepting and refilling worker slots. "
        "Release leases only after the worker stops. Keep queue/decisions current. "
        "Never kill processes outside your ownership.\n"
        "Claude settings.json and hooks do not activate in Codex. Tool filtering and delegation "
        "outside supported runtime controls are behavioral rules, not enforced hooks. "
        "If delegation is unavailable, report that limitation instead of pretending workers ran.\n"
    ) + END + "\n"


def install(project):
    project = Path(project).resolve()
    if not project.is_dir():
        raise ValueError("Project directory does not exist")
    changes = {}
    for name in roles():
        changes[project / ".codex/agents" / ("game-studio-" + name + ".toml")] = toml_role(name)
    for folder in sorted((ROOT / "skills").iterdir()):
        if not (folder / "SKILL.md").is_file():
            continue
        source = read(folder / "SKILL.md")
        frontmatter = source.split("---", 2)[1].strip()
        changes[project / ".agents/skills" / folder.name / "SKILL.md"] = (
            "---\n" + frontmatter + "\n---\n\n" + MARK + "\n\n"
            "Read and follow the canonical skill at " + str(folder / "SKILL.md") + ".\n"
            "For Codex runtime behavior also read " + str(ROOT / "skills/game-studio/references/codex.md") + ".\n"
            "Resolve its references and templates against that canonical skill directory.\n")
    agents = project / "AGENTS.md"
    previous = read(agents) if agents.exists() else ""
    if previous.count(BEGIN) != previous.count(END) or previous.count(BEGIN) > 1:
        raise ValueError("Malformed adapter block in AGENTS.md; no files changed")
    if BEGIN in previous and previous.index(END) < previous.index(BEGIN):
        raise ValueError("Malformed adapter block in AGENTS.md; no files changed")
    if BEGIN in previous:
        start, stop = previous.index(BEGIN), previous.index(END) + len(END)
        new_agents = previous[:start] + coordinator_block().rstrip() + previous[stop:]
    else:
        new_agents = previous + ("\n\n" if previous else "") + coordinator_block()
    # Check all collisions before writing. Never replace an unrelated role or skill.
    for path in changes:
        if path.exists() and MARK not in read(path):
            raise ValueError("Unmanaged destination already exists: " + str(path))
    changes[agents] = new_agents
    config = project / ".codex/game-studio/project.md"
    if not config.exists() and not any((project / p).exists() for p in (
            ".claude/game-studio/project.md", ".claude/skills/game-studio/project.md")):
        changes[config] = read(ROOT / "skills/game-studio/project.example.md")
    for path, content in changes.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return {"project": str(project), "workers": len(roles()), "files": len(changes),
            "next": "Fill project.md paths/caps, restart Codex and verify role discovery. Re-run install after plugin updates."}


def brief(args):
    project = Path(args.project).resolve()
    task = read(args.task_file)
    if re.search(r"<[a-zA-Z_][^>\n]*>", task):
        raise ValueError("Task brief contains unfilled template placeholders")
    configs = [project / p for p in (".codex/game-studio/project.md", ".claude/game-studio/project.md",
                                   ".claude/skills/game-studio/project.md")]
    config = next((p for p in configs if p.exists()), None)
    if not config:
        raise ValueError("Missing studio project.md; install and configure first")
    rules = read(ROOT / "skills/game-studio/references/worker-rules.md")
    return {"task_name": args.task_name, "fork_turns": "none", "model": MODELS[args.tier],
            "message": instructions(args.role) + "\n\nWORKSPACE: " + str(project) +
            "\nCHUNK MODEL: " + MODELS[args.tier] + "\n\nCANONICAL WORKER RULES\n" + rules +
            "\n\nPROJECT SETTINGS AND HARD LIMITS\n" + read(config) + "\n\nTASK BRIEF\n" + task}


def preflight(args):
    project = Path(args.project).resolve()
    free = shutil.disk_usage(project).free
    if args.min_free_gib < 0 or args.max_workers < 1 or args.active_workers < 0 or args.max_engine_runs < 0:
        raise ValueError("Invalid resource cap")
    problems = []
    if free < args.min_free_gib * 1024**3:
        problems.append("Free disk below minimum")
    if args.active_workers >= args.max_workers:
        problems.append("Worker cap reached")
    count = None
    if args.engine_process and args.max_engine_runs:
        if sys.platform == "win32":
            output = subprocess.check_output(["tasklist", "/FO", "CSV", "/NH"], text=True)
            names = [row[0] for row in csv.reader(io.StringIO(output)) if row]
        else:
            names = subprocess.check_output(["ps", "-A", "-o", "comm="], text=True).splitlines()
        count = sum(args.engine_process.casefold() in n.casefold() for n in names)
        if count >= args.max_engine_runs:
            problems.append("Engine process cap reached")
    return {"ok": not problems, "free_bytes": free, "engine_processes": count, "problems": problems}


def lease(args):
    if not args.resource.strip() or not args.owner.strip():
        raise ValueError("Resource and owner must be nonempty")
    base = Path(args.project).resolve() / ".codex/game-studio/locks"
    key = hashlib.sha256(args.resource.encode()).hexdigest()
    path = base / key
    if args.action == "claim":
        base.mkdir(parents=True, exist_ok=True)
        try:
            path.mkdir()  # Atomic: exactly one claimant wins.
        except FileExistsError:
            raise ValueError("Resource already leased: " + args.resource)
        try:
            (path / "owner.json").write_text(json.dumps({"owner": args.owner, "resource": args.resource}), encoding="utf-8")
        except Exception:
            path.rmdir()
            raise
    else:
        info = json.loads(read(path / "owner.json"))
        if info != {"owner": args.owner, "resource": args.resource}:
            raise ValueError("Only the recorded owner may release this lease")
        (path / "owner.json").unlink()
        path.rmdir()
    return {"action": args.action, "resource": args.resource, "owner": args.owner}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    p = commands.add_parser("install")
    p.add_argument("--project", required=True)
    p = commands.add_parser("brief")
    p.add_argument("--project", required=True)
    p.add_argument("--role", choices=roles(), required=True)
    p.add_argument("--tier", choices=MODELS, required=True)
    p.add_argument("--task-name", required=True)
    p.add_argument("--task-file", required=True)
    p = commands.add_parser("preflight")
    p.add_argument("--project", required=True)
    p.add_argument("--min-free-gib", type=float, required=True)
    p.add_argument("--max-workers", type=int, required=True)
    p.add_argument("--active-workers", type=int, required=True)
    p.add_argument("--engine-process", default="")
    p.add_argument("--max-engine-runs", type=int, default=0)
    p = commands.add_parser("lease")
    p.add_argument("action", choices=["claim", "release"])
    p.add_argument("--project", required=True)
    p.add_argument("--resource", required=True)
    p.add_argument("--owner", required=True)
    args = parser.parse_args()
    try:
        result = {"install": lambda: install(args.project), "brief": lambda: brief(args),
                  "preflight": lambda: preflight(args), "lease": lambda: lease(args)}[args.command]()
        print(json.dumps(result, ensure_ascii=False, indent=2))
        return 1 if result.get("ok") is False else 0
    except (ValueError, OSError, subprocess.SubprocessError) as error:
        print(str(error), file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
